### ISSUE TITLE
invalid UTF-8 data when serializing a protocol buffer

### ISSUE THREAD

**Issue by littleningmeng** [bruce30262/libprotobuf-mutator_fuzzing_learning#6]
The field type is string, when I call Mutate method, the error blow occured.

[libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'xxxxx' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Comment by bruce30262** [comment]
Please elaborate more on the details of your issue, like what kind of protobuf message structure you're using ? How to reproduce the issue ? ...etc.

Also please make sure that this issue is related to this repository, since after some googling, I believe this has something to do with [this post on stackoverflow.com](https://stackoverflow.com/questions/15139449/google-protocol-buffer-error-encountered-string-containing-invalid-utf-8-data), which has nothing to do with the code in this repo. If you read the [document](https://developers.google.com/protocol-buffers/docs/proto#scalar), you'll know that `string` can only contain UTF-8 encoded or 7-bit ASCII text, so if you're fuzzing a `string` member and let it contain some invalid UTF-8 data, you'll definitely run into an error, in that case, you should use the `bytes` message field instead of `string`.

I'm closing this issue since I highly doubt that this has something to do with this repository. If you still think that the problem is cause by the code in this repo, feel free to re-open this issue, however make sure to provide enough details or else I won't be convinced and will probably ignore it.

**Comment by littleningmeng** [comment]
copy that
thanks a lot
