### ISSUE TITLE
About protoc version

### ISSUE THREAD

**Issue by DuckRui** [bruce30262/libprotobuf-mutator_fuzzing_learning#7]
Hello, I want to learn about how to combine afl++ and libprotobuf-mutator. I fellow your command "cmake .. -GNinja -DCMAKE_C_COMPILER=clang-11 \
-DCMAKE_CXX_COMPILER=clang++-11 \
-DCMAKE_BUILD_TYPE=Debug \
-DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON \
-DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" "
This will install protoc in libprotobuf-mutator/build/external.protobuf/bin/ , and the version of protoc is 3.17.3.
I fellow your tutorial in 5_libprotobuf_aflpp_custom_mutator_input and usd command make try to create lpm_aflpp_custom_mutator_input.so.But there has some trouble seems like because of protoc version
![image](https://user-images.githubusercontent.com/41203418/139387250-e525052b-fff1-48df-af72-d7b7020f093d.png)
Looks like two questions, first is the version of protoc, second is can't find inlined_string_field.h. Can you help me? Thank you very much!

**Comment by DuckRui** [comment]
I can use the protoc that I generated to generate  test.pb.cc and test.pb.h instead of you provide. Then I can make successfully. In other tutorials, can you provide source code  of test.proto, so that I can generate  test.pb.cc and test.pb.h by myself? Because you provide these two files don't fit my version. Thank you very much!

**Comment by bruce30262** [comment]
The source code of `test.proto` is in [1_simple_protobuf](https://github.com/bruce30262/libprotobuf-mutator_fuzzing_learning/tree/2b0cea211289d89413cbfbe8b0f433ddb6e00f36/1_simple_protobuf). Also the problem you encounter have been mentioned in the [How to upgrade the environment](https://github.com/bruce30262/libprotobuf-mutator_fuzzing_learning#how-to-upgrade-the-environment) section of project README : 

> Re-compile the protobuf with newer protoc and replace those *.cc & *.h with new ones.

So yes you definitely need to build your own version of test.pb.cc and test.pb.h in order to build the binary. The message in README might not be clear enough, I might update the repo's README to remind everyone the importance of generating your own version of test.pb.cc & test.pb.h.

**Comment by bruce30262** [comment]
@DuckRui does my comment above solve your problem ? If so please let me know so we can close this issue

**Comment by DuckRui** [comment]
> @DuckRui does my comment above solve your problem ? If so please let me know so we can close this issue

Yes, thank you very much to help me.

**Comment by bruce30262** [comment]
No problem, closing issue.
